### ISSUE TITLE
Total number of unique contracts is broken

### ISSUE THREAD

**Issue by frol** [telezhnaya/near-analytics#5]
mainnet (there should be 800+ unique contracts):

![image](https://user-images.githubusercontent.com/304265/134982589-d6cb8822-692d-4d85-9468-201acd098b1e.png)

testnet (there should be 17k+ unique contracts):

![image](https://user-images.githubusercontent.com/304265/134982681-0fa83b23-8c71-4098-a1f9-345013df0033.png)

**Comment by telezhnaya** [comment]
@frol 
I forgot to remove some code on Explorer side
I need to remove this logic https://github.com/near/near-explorer/blob/master/backend/src/stats.js#L255-L279
And change SQL a little

I'm not sure why it does not work with the current implementation, but anyway it's better to rewrite it

**Comment by telezhnaya** [comment]
https://github.com/near/near-explorer/pull/747
